version: '3.8'
services:
  twc-db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: nest
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    networks:
      - twc

networks:
  twc:
    driver: bridge
